export const APPLY_LOADING_REQUEST = "APPLY_LOADING_REQUEST";
export const APPLY_LOADING_FAILURE = "APPLY_LOADING_FAILURE";
export const APPLY_LOADING_SUCCESS = "APPLY_LOADING_SUCCESS";

export const APPLY_SEARCH_REQUEST="APPLY_SEARCH_REQUEST";
export const APPLY_SEARCH_FAILURE="APPLY_SEARCH_FAILURE";
export const APPLY_SEARCH_SUCCESS="APPLY_SEARCH_SUCCESS";

export const APPLY_DELETE_REQUEST="APPLY_DELETE_REQUEST";
export const APPLY_DELETE_FAILURE="APPLY_DELETE_FAILURE";
export const APPLY_DELETE_SUCCESS="APPLY_DELETE_SUCCESS";

export const APPLY_DETAIL_REQUEST="APPLY_DETAIL_REQUEST";
export const APPLY_DETAIL_FAILURE="APPLY_DETAIL_FAILURE";
export const APPLY_DETAIL_SUCCESS="APPLY_DETAIL_SUCCESS";

export const REVIEW_ACCEPT_REQUEST="REVIEW_ACCEPT_REQUEST";
export const REVIEW_ACCEPT_FAILURE="REVIEW_ACCEPT_FAILURE";
export const REVIEW_ACCEPT_SUCCESS="REVIEW_ACCEPT_SUCCESS";

export const REVIEW_REJECT_REQUEST="REVIEW_REJECT_REQUEST";
export const REVIEW_REJECT_FAILURE="REVIEW_REJECT_FAILURE";
export const REVIEW_REJECT_SUCCESS="REVIEW_REJECT_SUCCESS";