export const BOARD_LOADING_REQUEST = "BOARD_LOADING_REQUEST";
export const BOARD_LOADING_FAILURE = "BOARD_LOADING_FAILURE";
export const BOARD_LOADING_SUCCESS = "BOARD_LOADING_SUCCESS";

//POST_UPLOAD_REQUEST

export const BOARD_SEARCH_REQUEST="BOARD_SEARCH_REQUEST";
export const BOARD_SEARCH_FAILURE="BOARD_SEARCH_FAILURE";
export const BOARD_SEARCH_SUCCESS="BOARD_SEARCH_SUCCESS";

export const BOARD_DELETE_REQUEST="BOARD_DELETE_REQUEST";
export const BOARD_DELETE_FAILURE="BOARD_DELETE_FAILURE";
export const BOARD_DELETE_SUCCESS="BOARD_DELETE_SUCCESS";

export const BOARD_DETAIL_REQUEST="BOARD_DETAIL_REQUEST";
export const BOARD_DETAIL_FAILURE="BOARD_DETAIL_FAILURE";
export const BOARD_DETAIL_SUCCESS="BOARD_DETAIL_SUCCESS";

export const BOARD_MODIFI_REQUEST="BOARD_MODIFI_REQUEST";
export const BOARD_MODIFI_FAILURE="BOARD_MODIFI_FAILURE";
export const BOARD_MODIFI_SUCCESS="BOARD_MODIFI_SUCCESS";