export const PROFILE_LOADING_REQUEST = "PROFILE_LOADING_REQUEST";
export const PROFILE_LOADING_FAILURE = "PROFILE_LOADING_FAILURE";
export const PROFILE_LOADING_SUCCESS = "PROFILE_LOADING_SUCCESS";

//POST_UPLOAD_REQUEST

export const PROFILE_SEARCH_REQUEST="PROFILE_SEARCH_REQUEST";
export const PROFILE_SEARCH_FAILURE="PROFILE_SEARCH_FAILURE";
export const PROFILE_SEARCH_SUCCESS="PROFILE_SEARCH_SUCCESS";

export const PROFILE_DELETE_REQUEST="PROFILE_DELETE_REQUEST";
export const PROFILE_DELETE_FAILURE="PROFILE_DELETE_FAILURE";
export const PROFILE_DELETE_SUCCESS="PROFILE_DELETE_SUCCESS";

export const PROFILE_DETAIL_REQUEST="PROFILE_DETAIL_REQUEST";
export const PROFILE_DETAIL_FAILURE="PROFILE_DETAIL_FAILURE";
export const PROFILE_DETAIL_SUCCESS="PROFILE_DETAIL_SUCCESS";