export const REPORT_LOADING_REQUEST = "REPORT_LOADING_REQUEST";
export const REPORT_LOADING_FAILURE = "REPORT_LOADING_FAILURE";
export const REPORT_LOADING_SUCCESS = "REPORT_LOADING_SUCCESS";

export const REPORT_SEARCH_REQUEST="REPORT_SEARCH_REQUEST";
export const REPORT_SEARCH_FAILURE="REPORT_SEARCH_FAILURE";
export const REPORT_SEARCH_SUCCESS="REPORT_SEARCH_SUCCESS";

export const REPORT_DELETE_REQUEST="REPORT_DELETE_REQUEST";
export const REPORT_DELETE_FAILURE="REPORT_DELETE_FAILURE";
export const REPORT_DELETE_SUCCESS="REPORT_DELETE_SUCCESS";