export const REPORT_LOADING_REQUEST = "REPORT_LOADING_REQUEST";
export const REPORT_LOADING_FAILURE = "REPORT_LOADING_FAILURE";
export const REPORT_LOADING_SUCCESS = "REPORT_LOADING_SUCCESS";

export const REPORT_SEARCH_REQUEST="REPORT_SEARCH_REQUEST";
export const REPORT_SEARCH_FAILURE="REPORT_SEARCH_FAILURE";
export const REPORT_SEARCH_SUCCESS="REPORT_SEARCH_SUCCESS";

export const REPORT_DETAIL_REQUEST="REPORT_DETAIL_REQUEST";
export const REPORT_DETAIL_FAILURE="REPORT_DETAIL_FAILURE";
export const REPORT_DETAIL_SUCCESS="REPORT_DETAIL_SUCCESS";