export const TAG_LOADING_REQUEST = "TAG_LOADING_REQUEST";
export const TAG_LOADING_FAILURE = "TAG_LOADING_FAILURE";
export const TAG_LOADING_SUCCESS = "TAG_LOADING_SUCCESS";

//POST_UPLOAD_REQUEST

export const TAG_SEARCH_REQUEST="TAG_SEARCH_REQUEST";
export const TAG_SEARCH_FAILURE="TAG_SEARCH_FAILURE";
export const TAG_SEARCH_SUCCESS="TAG_SEARCH_SUCCESS";

export const TAG_DELETE_REQUEST="TAG_DELETE_REQUEST";
export const TAG_DELETE_FAILURE="TAG_DELETE_FAILURE";
export const TAG_DELETE_SUCCESS="TAG_DELETE_SUCCESS";

export const TAG_UPLOADING_REQUEST="TAG_UPLOADING_REQUEST";
export const TAG_UPLOADING_FAILURE="TAG_UPLOADING_FAILURE";
export const TAG_UPLOADING_SUCCESS="TAG_UPLOADING_SUCCESS";
