export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";


export const USER_SEARCH_REQUEST="USER_SEARCH_REQUEST";
export const USER_SEARCH_FAILURE="USER_SEARCH_FAILURE";
export const USER_SEARCH_SUCCESS="USER_SEARCH_SUCCESS";



export const USER_DETAIL_REQUEST="USER_DETAIL_REQUEST";
export const USER_DETAIL_FAILURE="USER_DETAIL_FAILURE";
export const USER_DETAIL_SUCCESS="USER_DETAIL_SUCCESS";

export const USER_DELETE_REQUEST="USER_DELETE_REQUEST";
export const USER_DELETE_FAILURE="USER_DELETE_FAILURE";
export const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS";